"""add professional fields to reminders

Revision ID: 2f7d7d47598c
Revises: 003_tasks_and_integrations
Create Date: 2026-09-03 19:09:01.804039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f7d7d47598c'
down_revision: Union[str, Sequence[str], None] = '003_tasks_and_integrations'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_conversations_user_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.add_column('reminders', sa.Column('project', sa.String(), nullable=True))
    op.add_column('reminders', sa.Column('priority', sa.String(), nullable=False, server_default='medium'))
    op.add_column('reminders', sa.Column('estimated_minutes', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_reminders_user_id'), table_name='reminders')
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    op.alter_column('user_integrations', 'provider',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_user_integrations_user_id'), table_name='user_integrations')
    op.create_index(op.f('ix_user_integrations_user_id'), 'user_integrations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_integrations_user_id'), table_name='user_integrations')
    op.create_index(op.f('idx_user_integrations_user_id'), 'user_integrations', ['user_id'], unique=False)
    op.alter_column('user_integrations', 'provider',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.create_index(op.f('idx_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    op.drop_column('reminders', 'estimated_minutes')
    op.drop_column('reminders', 'priority')
    op.drop_column('reminders', 'project')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.create_index(op.f('idx_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    # ### end Alembic commands ###
